# Generated by Django 5.0.7 on 2024-10-10 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clients/')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CTAContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField()),
                ('button_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('phone_number', models.CharField(max_length=20)),
                ('footer_text', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('button_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddConstraint(
            model_name='ctacontent',
            constraint=models.UniqueConstraint(fields=('id',), name='single_cta_content'),
        ),
        migrations.AddConstraint(
            model_name='footercontent',
            constraint=models.UniqueConstraint(fields=('id',), name='single_footer_content'),
        ),
        migrations.AddConstraint(
            model_name='herocontent',
            constraint=models.UniqueConstraint(fields=('id',), name='single_hero_content'),
        ),
        migrations.AddField(
            model_name='servicebulletpoint',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='api.service'),
        ),
    ]
