# Generated by Django 5.0.1 on 2024-11-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aboutcontent_contactus_processphoto_short_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceBulletPoint',
        ),
    ]
