# Generated by Django 5.0.1 on 2024-11-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_servicebulletpoint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ctacontent',
            name='single_cta_content',
        ),
        migrations.AddField(
            model_name='ctacontent',
            name='button_link',
            field=models.URLField(default='http://www.example.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ctacontent',
            name='button_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ctacontent',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
