# Generated by Django 5.0.1 on 2024-12-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_ctacontent_single_cta_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercontent',
            name='location',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
