# Generated by Django 5.0.1 on 2025-01-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_footercontent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
    ]
