# Generated by Django 5.0.1 on 2025-01-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_formsubmission_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
